export default function Head() {
  return (
    <>
      <title>Restaurants and Restaurant Reservations | OpenTable</title>

      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta
        name="description"
        content="Make online reservations, read restaurant reviews from diners, and earn points towards free meals. OpenTable is a real-time online reservation network for fine dining restaurants."
      />
      <meta
        name="keywords"
        content="restaurant reservations, online restaurant reservations, restaurant management software, opentable, open table"
      />

      <link
        rel="icon"
        sizes="16x16"
        href="//cdn.otstatic.com/cfe/14/images/favicon-16-378b8c.png"
      />
      <link
        rel="icon"
        sizes="32x32"
        href="//cdn.otstatic.com/cfe/14/images/favicon-32-5ec316.png"
      />
      <link
        rel="icon"
        sizes="48x48"
        href="//cdn.otstatic.com/cfe/14/images/favicon-48-0d2162.png"
      />
      <link
        rel="icon"
        sizes="64x64"
        href="//cdn.otstatic.com/cfe/14/images/favicon-64-bf0643.png"
      />
      <link
        rel="icon"
        sizes="128x128"
        href="//cdn.otstatic.com/cfe/14/images/favicon-128-15926e.png"
      />
    </>
  );
}
